version: 2
jobs:
  install:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
      - run:
          name: Install dependancies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}

  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist

  deploy:
    working_directory: ~/repo
    docker:
      - image: rdfriedl/circleci-node-aws
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Deploy to s3 bucket
          command: |
            aws configure set preview.cloudfront true && \
            aws s3 rm s3://${S3_BUCKET} --recursive && \
            aws s3 sync /tmp/workspace/dist s3://${S3_BUCKET} --acl public-read && \
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master